// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_lYNDfwlt5wNQ_CUdYZM_I350DjnDxo',
    appId: '1:921384333583:web:8b04fdcc6b7e1122c04e7a',
    messagingSenderId: '921384333583',
    projectId: 'our-garden-d2dcf',
    authDomain: 'our-garden-d2dcf.firebaseapp.com',
    storageBucket: 'our-garden-d2dcf.firebasestorage.app',
    measurementId: 'G-Z0089K7LC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_fsqdk-7eAQyAGv0Y-gl-s6QIytkuncM',
    appId: '1:921384333583:android:93afcbdbc05146fdc04e7a',
    messagingSenderId: '921384333583',
    projectId: 'our-garden-d2dcf',
    storageBucket: 'our-garden-d2dcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdBFk3rx3C_hlcJnFlRdJEgyfAeBwG9fk',
    appId: '1:921384333583:ios:32e63d25dff115dac04e7a',
    messagingSenderId: '921384333583',
    projectId: 'our-garden-d2dcf',
    storageBucket: 'our-garden-d2dcf.firebasestorage.app',
    iosClientId: '921384333583-un9g4liqqk79rfqhhoer11o3raigaaed.apps.googleusercontent.com',
    iosBundleId: 'com.plantculture',
  );
}
